// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lesson9/homework/internal/ports/grpc/service.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	lesson9/homework/internal/ports/grpc/service.proto

It has these top-level messages:
	Mode
	CreateAdRequest
	ChangeAdStatusRequest
	UpdateAdRequest
	AdResponse
	ListAdResponse
	CreateUserRequest
	UserResponse
	GetUserRequest
	DeleteUserRequest
	DeleteAdRequest
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModeType int32

const (
	ModeType_Default    ModeType = 0
	ModeType_All        ModeType = 1
	ModeType_ByAuthor   ModeType = 2
	ModeType_ByCreation ModeType = 3
	ModeType_ByTitle    ModeType = 4
)

var ModeType_name = map[int32]string{
	0: "Default",
	1: "All",
	2: "ByAuthor",
	3: "ByCreation",
	4: "ByTitle",
}
var ModeType_value = map[string]int32{
	"Default":    0,
	"All":        1,
	"ByAuthor":   2,
	"ByCreation": 3,
	"ByTitle":    4,
}

func (x ModeType) String() string {
	return proto.EnumName(ModeType_name, int32(x))
}
func (ModeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Mode struct {
	Mode ModeType `protobuf:"varint,1,opt,name=mode,enum=ad.ModeType" json:"mode,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Mode_AuthorId
	//	*Mode_Title
	//	*Mode_Time
	Data isMode_Data `protobuf_oneof:"Data"`
}

func (m *Mode) Reset()                    { *m = Mode{} }
func (m *Mode) String() string            { return proto.CompactTextString(m) }
func (*Mode) ProtoMessage()               {}
func (*Mode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isMode_Data interface{ isMode_Data() }

type Mode_AuthorId struct {
	AuthorId int64 `protobuf:"varint,2,opt,name=authorId,oneof"`
}
type Mode_Title struct {
	Title string `protobuf:"bytes,3,opt,name=title,oneof"`
}
type Mode_Time struct {
	Time *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=time,oneof"`
}

func (*Mode_AuthorId) isMode_Data() {}
func (*Mode_Title) isMode_Data()    {}
func (*Mode_Time) isMode_Data()     {}

func (m *Mode) GetData() isMode_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Mode) GetMode() ModeType {
	if m != nil {
		return m.Mode
	}
	return ModeType_Default
}

func (m *Mode) GetAuthorId() int64 {
	if x, ok := m.GetData().(*Mode_AuthorId); ok {
		return x.AuthorId
	}
	return 0
}

func (m *Mode) GetTitle() string {
	if x, ok := m.GetData().(*Mode_Title); ok {
		return x.Title
	}
	return ""
}

func (m *Mode) GetTime() *google_protobuf.Timestamp {
	if x, ok := m.GetData().(*Mode_Time); ok {
		return x.Time
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Mode) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Mode_OneofMarshaler, _Mode_OneofUnmarshaler, _Mode_OneofSizer, []interface{}{
		(*Mode_AuthorId)(nil),
		(*Mode_Title)(nil),
		(*Mode_Time)(nil),
	}
}

func _Mode_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Mode)
	// Data
	switch x := m.Data.(type) {
	case *Mode_AuthorId:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.AuthorId))
	case *Mode_Title:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Title)
	case *Mode_Time:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Time); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Mode.Data has unexpected type %T", x)
	}
	return nil
}

func _Mode_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Mode)
	switch tag {
	case 2: // Data.authorId
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Data = &Mode_AuthorId{int64(x)}
		return true, err
	case 3: // Data.title
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Data = &Mode_Title{x}
		return true, err
	case 4: // Data.time
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Timestamp)
		err := b.DecodeMessage(msg)
		m.Data = &Mode_Time{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Mode_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Mode)
	// Data
	switch x := m.Data.(type) {
	case *Mode_AuthorId:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.AuthorId))
	case *Mode_Title:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Title)))
		n += len(x.Title)
	case *Mode_Time:
		s := proto.Size(x.Time)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateAdRequest struct {
	Title  string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Text   string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	UserId int64  `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *CreateAdRequest) Reset()                    { *m = CreateAdRequest{} }
func (m *CreateAdRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAdRequest) ProtoMessage()               {}
func (*CreateAdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAdRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateAdRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CreateAdRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ChangeAdStatusRequest struct {
	AdId      int64 `protobuf:"varint,1,opt,name=ad_id,json=adId" json:"ad_id,omitempty"`
	UserId    int64 `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Published bool  `protobuf:"varint,3,opt,name=published" json:"published,omitempty"`
}

func (m *ChangeAdStatusRequest) Reset()                    { *m = ChangeAdStatusRequest{} }
func (m *ChangeAdStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeAdStatusRequest) ProtoMessage()               {}
func (*ChangeAdStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChangeAdStatusRequest) GetAdId() int64 {
	if m != nil {
		return m.AdId
	}
	return 0
}

func (m *ChangeAdStatusRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangeAdStatusRequest) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

type UpdateAdRequest struct {
	AdId   int64  `protobuf:"varint,1,opt,name=ad_id,json=adId" json:"ad_id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Text   string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	UserId int64  `protobuf:"varint,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *UpdateAdRequest) Reset()                    { *m = UpdateAdRequest{} }
func (m *UpdateAdRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateAdRequest) ProtoMessage()               {}
func (*UpdateAdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateAdRequest) GetAdId() int64 {
	if m != nil {
		return m.AdId
	}
	return 0
}

func (m *UpdateAdRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateAdRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *UpdateAdRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type AdResponse struct {
	Id           int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title        string                     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Text         string                     `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	AuthorId     int64                      `protobuf:"varint,4,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	Published    bool                       `protobuf:"varint,5,opt,name=published" json:"published,omitempty"`
	CreationDate *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=CreationDate,json=creationDate" json:"CreationDate,omitempty"`
	UpdateTime   *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=UpdateTime,json=updateTime" json:"UpdateTime,omitempty"`
}

func (m *AdResponse) Reset()                    { *m = AdResponse{} }
func (m *AdResponse) String() string            { return proto.CompactTextString(m) }
func (*AdResponse) ProtoMessage()               {}
func (*AdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AdResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AdResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *AdResponse) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *AdResponse) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

func (m *AdResponse) GetCreationDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *AdResponse) GetUpdateTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type ListAdResponse struct {
	List []*AdResponse `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ListAdResponse) Reset()                    { *m = ListAdResponse{} }
func (m *ListAdResponse) String() string            { return proto.CompactTextString(m) }
func (*ListAdResponse) ProtoMessage()               {}
func (*ListAdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListAdResponse) GetList() []*AdResponse {
	if m != nil {
		return m.List
	}
	return nil
}

type CreateUserRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserResponse struct {
	Id    int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteAdRequest struct {
	AdId     int64 `protobuf:"varint,1,opt,name=ad_id,json=adId" json:"ad_id,omitempty"`
	AuthorId int64 `protobuf:"varint,2,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
}

func (m *DeleteAdRequest) Reset()                    { *m = DeleteAdRequest{} }
func (m *DeleteAdRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAdRequest) ProtoMessage()               {}
func (*DeleteAdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteAdRequest) GetAdId() int64 {
	if m != nil {
		return m.AdId
	}
	return 0
}

func (m *DeleteAdRequest) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func init() {
	proto.RegisterType((*Mode)(nil), "ad.Mode")
	proto.RegisterType((*CreateAdRequest)(nil), "ad.CreateAdRequest")
	proto.RegisterType((*ChangeAdStatusRequest)(nil), "ad.ChangeAdStatusRequest")
	proto.RegisterType((*UpdateAdRequest)(nil), "ad.UpdateAdRequest")
	proto.RegisterType((*AdResponse)(nil), "ad.AdResponse")
	proto.RegisterType((*ListAdResponse)(nil), "ad.ListAdResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "ad.CreateUserRequest")
	proto.RegisterType((*UserResponse)(nil), "ad.UserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "ad.GetUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "ad.DeleteUserRequest")
	proto.RegisterType((*DeleteAdRequest)(nil), "ad.DeleteAdRequest")
	proto.RegisterEnum("ad.ModeType", ModeType_name, ModeType_value)
}

func init() { proto.RegisterFile("lesson9/homework/internal/ports/grpc/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 700 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x8d, 0x7f, 0x9a, 0x38, 0xd3, 0x28, 0x4d, 0xb7, 0x5f, 0x3f, 0x42, 0xa8, 0x44, 0x64, 0x10,
	0x0a, 0x5c, 0xc4, 0x34, 0x20, 0x55, 0x20, 0x15, 0x29, 0x69, 0x24, 0x52, 0x01, 0x37, 0x6e, 0x7a,
	0xc3, 0x0d, 0xda, 0x66, 0xb7, 0x89, 0x85, 0x63, 0x1b, 0xef, 0x1a, 0xc8, 0x9b, 0xf0, 0x1e, 0x3c,
	0x1f, 0x12, 0xf2, 0x2e, 0x1b, 0xff, 0xd4, 0x55, 0xe1, 0xce, 0xbb, 0x3b, 0x33, 0xe7, 0xcc, 0x9c,
	0x33, 0x09, 0x8c, 0x7c, 0xca, 0x58, 0x18, 0xbc, 0x72, 0x56, 0xe1, 0x9a, 0x7e, 0x0b, 0xe3, 0xcf,
	0x8e, 0x17, 0x70, 0x1a, 0x07, 0xd8, 0x77, 0xa2, 0x30, 0xe6, 0xcc, 0x59, 0xc6, 0xd1, 0xc2, 0x61,
	0x34, 0xfe, 0xea, 0x2d, 0xe8, 0x30, 0x8a, 0x43, 0x1e, 0x22, 0x1d, 0x93, 0xde, 0xc3, 0x65, 0x18,
	0x2e, 0x7d, 0xea, 0x88, 0x9b, 0xab, 0xe4, 0xda, 0xe1, 0xde, 0x9a, 0x32, 0x8e, 0xd7, 0x91, 0x0c,
	0xb2, 0x7f, 0x68, 0x60, 0x7e, 0x08, 0x09, 0x45, 0x7d, 0x30, 0xd7, 0x21, 0xa1, 0x5d, 0xad, 0xaf,
	0x0d, 0xda, 0xa3, 0xd6, 0x10, 0x93, 0x61, 0x7a, 0x3f, 0xdf, 0x44, 0xd4, 0x15, 0x2f, 0xe8, 0x08,
	0x2c, 0x9c, 0xf0, 0x55, 0x18, 0x9f, 0x93, 0xae, 0xde, 0xd7, 0x06, 0xc6, 0xac, 0xe6, 0x6e, 0x6f,
	0xd0, 0xff, 0xb0, 0xc3, 0x3d, 0xee, 0xd3, 0xae, 0xd1, 0xd7, 0x06, 0xcd, 0x59, 0xcd, 0x95, 0x47,
	0xf4, 0x1c, 0xcc, 0x14, 0xb3, 0x6b, 0xf6, 0xb5, 0xc1, 0xee, 0xa8, 0x37, 0x94, 0x84, 0x86, 0x8a,
	0xd0, 0x70, 0xae, 0x08, 0xcd, 0x6a, 0xae, 0x88, 0x9c, 0xd4, 0xc1, 0x9c, 0x62, 0x8e, 0xed, 0x39,
	0xec, 0x9d, 0xc5, 0x14, 0x73, 0x3a, 0x26, 0x2e, 0xfd, 0x92, 0x50, 0xc6, 0xd1, 0x7f, 0x0a, 0x24,
	0x65, 0xd9, 0x54, 0x10, 0x08, 0x4c, 0x4e, 0xbf, 0x73, 0x41, 0xaa, 0xe9, 0x8a, 0x6f, 0x74, 0x0f,
	0x1a, 0x09, 0xa3, 0xf1, 0x27, 0x8f, 0x08, 0x42, 0x86, 0x5b, 0x4f, 0x8f, 0xe7, 0xc4, 0x5e, 0xc0,
	0xe1, 0xd9, 0x0a, 0x07, 0x4b, 0x3a, 0x26, 0x17, 0x1c, 0xf3, 0x84, 0xa9, 0xda, 0x07, 0xb0, 0x83,
	0x49, 0x1a, 0xaf, 0x89, 0x78, 0x13, 0x93, 0x73, 0x92, 0x2f, 0xa3, 0xe7, 0xcb, 0xa0, 0x23, 0x68,
	0x46, 0xc9, 0x95, 0xef, 0xb1, 0x15, 0x95, 0x08, 0x96, 0x9b, 0x5d, 0xd8, 0x1e, 0xec, 0x5d, 0x46,
	0xa4, 0x40, 0xbd, 0xb2, 0xfc, 0xb6, 0x1f, 0xbd, 0xaa, 0x1f, 0xa3, 0xba, 0x1f, 0xb3, 0xd0, 0xcf,
	0x2f, 0x0d, 0x20, 0x45, 0x61, 0x51, 0x18, 0x30, 0x8a, 0xda, 0xa0, 0x6f, 0x31, 0x74, 0xef, 0x5f,
	0x10, 0x1e, 0x40, 0x53, 0x8a, 0x99, 0x61, 0x64, 0xea, 0x16, 0xda, 0xdd, 0x29, 0xb5, 0x8b, 0xde,
	0x40, 0x4b, 0x28, 0xe5, 0x85, 0xc1, 0x14, 0x73, 0xda, 0xad, 0xdf, 0xa5, 0xb5, 0xdb, 0x5a, 0xe4,
	0xe2, 0xd1, 0x6b, 0x00, 0x39, 0xae, 0x34, 0xa0, 0xdb, 0xb8, 0x33, 0x1b, 0x92, 0x6d, 0xb4, 0xfd,
	0x12, 0xda, 0xef, 0x3d, 0xc6, 0x73, 0x23, 0xb0, 0xc1, 0xf4, 0x3d, 0xc6, 0xbb, 0x5a, 0xdf, 0x18,
	0xec, 0x8e, 0xda, 0xa9, 0x93, 0xb3, 0x57, 0x57, 0xbc, 0xd9, 0xa7, 0xb0, 0x2f, 0xbd, 0x75, 0xc9,
	0x68, 0xac, 0x24, 0x42, 0x60, 0x06, 0x78, 0xad, 0xcc, 0x25, 0xbe, 0xd3, 0xf9, 0xd1, 0x35, 0xf6,
	0x7c, 0x35, 0x3f, 0x71, 0xb0, 0x67, 0xd0, 0x92, 0x89, 0xb7, 0x4c, 0x5d, 0x55, 0xd2, 0xab, 0x2a,
	0x19, 0xf9, 0x4a, 0x7d, 0x68, 0xbf, 0xa5, 0x3c, 0xcf, 0xa2, 0x54, 0xcb, 0x7e, 0x04, 0xfb, 0x53,
	0xea, 0xd3, 0x22, 0xd5, 0x72, 0xd0, 0x19, 0xec, 0xc9, 0xa0, 0x3b, 0x0c, 0x57, 0x10, 0x59, 0x2f,
	0x8a, 0xfc, 0xec, 0x1d, 0x58, 0x6a, 0xe5, 0xd1, 0x2e, 0x34, 0xa6, 0xf4, 0x1a, 0x27, 0x3e, 0xef,
	0xd4, 0x50, 0x03, 0x8c, 0xb1, 0xef, 0x77, 0x34, 0xd4, 0x02, 0x6b, 0xb2, 0x19, 0x8b, 0xf8, 0x8e,
	0x8e, 0xda, 0x00, 0x93, 0x8d, 0x12, 0xbe, 0x63, 0xa4, 0x39, 0x93, 0xcd, 0x3c, 0x35, 0x58, 0xc7,
	0x1c, 0xfd, 0x34, 0xa0, 0x39, 0x26, 0x17, 0xf2, 0x17, 0x09, 0x1d, 0x83, 0xa5, 0x76, 0x19, 0x1d,
	0xa4, 0x8a, 0x94, 0x36, 0xbb, 0x57, 0x92, 0xc9, 0xae, 0xa1, 0x53, 0x68, 0x17, 0x17, 0x15, 0xdd,
	0x17, 0x89, 0x55, 0xcb, 0x5b, 0x91, 0x7e, 0x0c, 0x96, 0x5a, 0x41, 0x89, 0x58, 0x5a, 0xc8, 0x8a,
	0x94, 0xa7, 0xd0, 0x90, 0x56, 0x62, 0xc8, 0x52, 0xbf, 0x7f, 0x3d, 0x94, 0x7e, 0x15, 0x1d, 0x66,
	0xd7, 0xd0, 0x09, 0x40, 0xe6, 0x1f, 0x74, 0x98, 0x75, 0x94, 0x13, 0xa9, 0xd7, 0x11, 0xb0, 0x39,
	0x9f, 0x08, 0x5a, 0x8d, 0x3f, 0x7a, 0x23, 0x51, 0xb9, 0x28, 0x7e, 0x65, 0xca, 0x09, 0x40, 0x66,
	0x00, 0x89, 0x75, 0xc3, 0x10, 0xb7, 0x60, 0x59, 0xca, 0x14, 0x72, 0x04, 0x25, 0x8b, 0xdc, 0x1c,
	0xc1, 0xe4, 0xc9, 0xc7, 0xc7, 0x7f, 0xf3, 0x4f, 0x73, 0x55, 0x17, 0x5b, 0xf9, 0xe2, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x88, 0x7d, 0x82, 0x25, 0x98, 0x06, 0x00, 0x00,
}
